name: jasa_cepat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.11.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # State Management
  flutter_bloc: ^8.1.3 
  
  # Fitur Lokasi & Peta
  geolocator: ^10.1.0      # Untuk mengambil koordinat GPS pengguna
  google_maps_flutter: ^2.5.3 # Untuk menampilkan peta dan lokasi tukang
  
  # Komunikasi & Chat (Realtime)
  firebase_core: ^2.24.0
  firebase_database: ^10.4.0 
  
  # Desain UI
  cached_network_image: ^3.3.1 # Menampilkan foto profil/jasa tanpa lemot

  # API Client (Pusat koneksi data internet/backend)
  dio: ^5.4.0 
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.15.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints.
  flutter_lints: ^6.0.0

  # Tambahkan package generator di bawah dev_dependencies agar bisa membuat splash otomatis
  flutter_native_splash: ^2.4.0

  # Package generator untuk logo aplikasi
  flutter_launcher_icons: ^0.13.1

# Konfigurasi warna layar splash awal bawaan HP (Warna Biru JasaCepat)
flutter_native_splash:
  color: "#2196F3"
  android_12:
    color: "#2196F3"

# Konfigurasi pembuatan logo aplikasi Android & iOS
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo polos.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is included.
  uses-material-design: true

  assets:
    - assets/images/